### PR TITLE
Update project compatibility

### PR DESCRIPTION
**Pull request by atrophiedbrain**

### CODE REVIEW

**Comment by tpapp** [comment]
Thanks for the update. Something is going in with CI that I need to investigate before merging this (it is probably unrelated), but I will try to do it soon.

**Comment by atrophiedbrain** [comment]
The CI issue was caused by the Manifest.toml specifying NLopt 0.5.1 still. After bumping the Manifest.toml NLopt version to 0.6.0, CI passed.

**Comment by tpapp** [comment]
Would you mind making another commit which just removes the `Manifest.toml`? I realized that's the best way since I wrote this package.

**Comment by atrophiedbrain** [comment]
Committed the requested deletion of `Manifest.toml`.

**Comment by tpapp** [comment]
Thanks for updating this PR, merging.

**Pull request merged**
