### PR TITLE
Connect with GalacticOptim

### PR DESCRIPTION
**Pull request by Manas2030**
This allows the package to use solvers from GalacticOptim except `QuadDirect` and also problems of type `EnsembleOptimizationProblem` aren't supported.

### CODE REVIEW

**Comment by Manas2030** [comment]
Hello @tpapp please let me know if there's any edits or suggestions you would like to be done in this PR. 
Also I was wondering if separating related pieces of code into different files from `MultistartOptimization.jl` would be a good idea. What do you think about this?

**Comment by tpapp** [comment]
@Manas2030: Thanks for the PR.

1. Please make sure that tests pass. Probably you need to add GalacticOptim to the project. (`pkg> add` ...). Though a conditional dependency through Requires.jl may be better as it is a heavy dependency. This would then suggest code in a separate file.
2. Make sure all types in `struct`s are concrete.
3. I am not sure why we need a new struct for the outer problem. Can we just use GalacticOptim as a local method? Probably you don't need to duplicate functionality in `sobol_starting_points` either.

**Comment by Manas2030** [comment]
Hello Tamas, thank you for your review!
I am working on the first 2 points as you mentioned.
For the the 3rd point, `GalacticOptim.solve` requires parameters passed in the objective function. 
Example- 
```
rosenbrock(x,p) =  (p[1] - x[1])^2 + p[2] * (x[2] - x[1]^2)^2
p  = [1.0,100.0]
```
But we can go around this by defining it like
```
my_rosenbrock(x,p=nothing) = (1.0 - x[1])^2 + 100.0 * (x[2] - x[1]^2)^2
```
So to not compromise the ability of passing parameters I defined the structs. But I understand it can also be done within a local method and I'll work on what you suggested if it seems like a better idea?

Also is it okay to keep the struct `GalacticOptimLocalMethod` as it would also let us decide function to be called in case there are  various versions of `local_minimization` in future?

**Comment by tpapp** [comment]
Sorry, I don't understand why GalacticOptim requires parameters in the function. Probably it has a reason, but this package just needs a function that maps a vector to a number. Perhaps a simple wrapper like
```julia
struct GalacticFunction{F,P}
    f::F
    p::P
end

(g::GalacticFunction)(x::AbstractVector) = g.f(x, g.p)
```
could work but please do consult the authors of that package for more details on this (feel free to ping me in those discussions).

I reorganized the API in #20 to make these kind of changes easier. Let me know if you have questions.

**Comment by Manas2030** [comment]
Hello @tpapp! Thank you for the newly organized API. This surely makes it easier to make changes!

Also I have made the following changes:
1) Added GalacticOptim as a dependency
2) Added some documentation (in docs/src/index.md) 
3) Updated MultistartOptimization.jl
4) Updated GalacticOptim.jl ( I have removed the struct `GalacticOptimMinimizationProblem` and the repetitive function `sobol_starting_points(minimization_problem::GalacticOptimMinimizationProblem, N::Integer,
                               use_threads::Bool)` and have only kept `maxiters` and `kwargs` as parameters in `GalacticOptimLocalMethod` to let the user decide maximum iterations allowed in every local search)

Also I am sorry there's a few repetitive commits which arised while shifting to the new API and then fetching (git fetch) those changes to my local machine

Please review this whenever it's possible for you and let me know if there's any suggestions or changes required. 🙂

**Comment by tpapp** [comment]
@Manas2030: Apologies for not yet getting to this, I hope to do this next week. If I don't, please do not hesitate to ping me.

**Comment by Manas2030** [comment]
Hello, @tpapp! Just pinging as a reminder. Please review whenever it's possible for you.

**Pull request closed without merging**
